# secret.yaml
{{- if eq .Values.secretstore.enabled false}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-config
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secret.postgres.db | b64enc }}
  POSTGRES_USER: {{ .Values.secret.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres.password | b64enc }}
  POSTGRES_HOST: {{ .Values.secret.postgres.host | b64enc }}
  POSTGRES_PORT: {{ .Values.secret.postgres.port | b64enc }}
  {{- if .Values.secret.ipfs.apiKey }}
  IPFS_API_KEY: {{ .Values.secret.ipfs.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.secret.ipfs.apiClient }}
  IPFS_API_CLIENT: {{ .Values.secret.ipfs.apiClient | b64enc }}
  {{- end }}
{{- end }}
