apiVersion: v1
kind: Service
metadata:
  creationTimestamp:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - name: {{ .Release.Name }}
    port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
