apiVersion: v1
kind: Service
metadata:
  creationTimestamp:
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ports:
  - name: {{ .Chart.Name }}
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  sessionAffinity: None
  clusterIP: None
