apiVersion: v1
data:
  LOG_LEVEL: {{ .Values.config.log.level }}
  OCEAN_PROVIDER_URL: {{ .Values.config.oceanProviderUrl }}
  OCEAN_PROVIDER_WORKERS: {{ .Values.config.oceanProviderWorkers | quote }}
  OCEAN_PROVIDER_TIMEOUT: {{ .Values.config.oceanProviderTimeout | quote }}
  OPERATOR_SERVICE_URL: {{ .Values.config.operatorServiceUrl }}
  AQUARIUS_URL: {{ .Values.config.aquariusUrl }}
  RBAC_SERVER_URL: {{ .Values.config.rbacUrl }}
  REQUEST_RETRIES: {{ .Values.config.requestRetries | quote }}
  ALLOW_NON_PUBLIC_IP: {{ .Values.config.allowNonPublicIp | quote }}
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-config
