apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: ARTIFACTS_PATH
          value: /ocean-provider/artifacts
        - name: RBAC_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: RBAC_SERVER_URL
              name: {{ .Release.Name }}-config
        - name: NETWORK_URL
          valueFrom:
            secretKeyRef:
              key: NETWORK_URL
              name: {{ .Release.Name }}-secret-config
        - name: INFURA_PROJECT_ID
          valueFrom:
            secretKeyRef:
              key: INFURA_PROJECT_ID
              name: {{ .Release.Name }}-secret-config
        - name: PROVIDER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: PROVIDER_PRIVATE_KEY
              name: {{ .Release.Name }}-secret-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: {{ .Release.Name }}-config
        - name: OCEAN_PROVIDER_URL
          valueFrom:
            configMapKeyRef:
              key: OCEAN_PROVIDER_URL
              name: {{ .Release.Name }}-config
        - name: OCEAN_PROVIDER_WORKERS
          valueFrom:
            configMapKeyRef:
              key: OCEAN_PROVIDER_WORKERS
              name: {{ .Release.Name }}-config
        - name: OCEAN_PROVIDER_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: OCEAN_PROVIDER_TIMEOUT
              name: {{ .Release.Name }}-config
        - name: OPERATOR_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: OPERATOR_SERVICE_URL
              name: {{ .Release.Name }}-config
        - name: AQUARIUS_URL
          valueFrom:
            configMapKeyRef:
              key: AQUARIUS_URL
              name: {{ .Release.Name }}-config
        name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8030
          name: http
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        {{- if .Values.secretstore.enabled }}
        volumeMounts:
        - name: {{ .Release.Name }}-{{ .Values.secretstore.provider }}-secrets
          mountPath: /mnt/secrets-store/
          readOnly: true
        {{- end }}
      {{- if .Values.secretstore.enabled }}
      volumes:
      - name: {{ .Release.Name }}-{{ .Values.secretstore.provider }}-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Release.Name }}-{{ .Values.secretstore.provider }}-secrets
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
