{{- if .Values.podAutoScaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}
spec:
  minReplicas: {{ .Values.podAutoScaler.minReplicas }}
  maxReplicas:  {{ .Values.podAutoScaler.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: {{ .Values.podAutoScaler.resource.averageUtilization }}
{{- end }}
