apiVersion: v1
name: ocean-compute-operator
version: 1.0.0
appVersion: 1.0.0
description: Ocean Operator Service v3
home: https://github.com/oceanprotocol/operator-engine
maintainers:
- name: Daimler TSS Malaysia
  email: dw_633_data-marketplace@daimler.com
